Repository hmcts/sscs-bulk-scan, pull requests merged in 2019-04, with the labels that each got.

#150 SSCS-5178 Bulk scan – ValidationException – Phone number does not mat…
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/integrationTest/resources/mappings/exception/case-creation-request.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request.json
  src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs-bulk-scan-pr-150

#178 Sscs 5219 update commons library
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs-bulk-scan-pr-178

#168 Upgrade common library to 0.0.157
  build.gradle
  config/owasp/suppressions.xml
Labels: DO NOT MERGE, ns:sscs-bulk-scan-pr-168

#167 SSCS-5081 - Upgrade cnp-java base to the latest
  Dockerfile
Labels: ns:sscs-bulk-scan-pr-167

#184 Update azurem version to 1.22.1
  config/owasp/suppressions.xml
  infrastructure/main.tf
Labels: ns:sscs-bulk-scan-pr-184

#189 Sscs 3936 bump java logging v3
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/main.tf
  infrastructure/variables.tf
  kubernetes/deployment.template.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/main/java/uk/gov/hmcts/reform/sscs/exceptions/CaseDataHelperException.java
  src/main/resources/application.yaml
Labels: ns:sscs-bulk-scan-pr-189

#194 SSCS-5444 use appellant evidence doc type
  build.gradle
  src/integrationTest/resources/mappings/exception/case-creation-request.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request.json
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
Labels: ns:sscs-bulk-scan-pr-194

#197 Upgrade common 2.0.3 v2
  build.gradle
Labels: ns:sscs-bulk-scan-pr-197

#200 Upgrade robotics common to 1.0.2
  build.gradle
Labels: ns:sscs-bulk-scan-pr-200

#201 Upgrade common library to 2.0.4
  build.gradle
Labels: ns:sscs-bulk-scan-pr-201

#204 SSCS-5499 Add SSCS1 as doc subtype
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
Labels: ns:sscs-bulk-scan-pr-204
