Repository hmcts/sscs-bulk-scan, pull requests merged in 2019-03, with the labels that each got.

#146 SSCS-5176 Bulk scan - java.lang.NullPointerException – Blank body for…
  build.gradle
  src/main/resources/application.yaml
Labels: ns:sscs-bulk-scan-pr-146

#147 Derive ase_name from core compute environment
  infrastructure/main.tf
Labels: ns:sscs-bulk-scan-pr-147

#145 Task/sidam test saat
  Jenkinsfile_parameterized
  infrastructure/main.tf
  infrastructure/saat.tfvars
  kubernetes/config.saat.yaml
  src/main/resources/application.yaml
Labels: ns:sscs-bulk-scan-pr-145

#149 Upgrade pdf common to 0.0.106
  build.gradle
Labels: ns:sscs-bulk-scan-pr-149

#151 point bulk scan to SIDAM in AAT and AKS
  Jenkinsfile_CNP
  config/owasp/suppressions.xml
  infrastructure/aat.tfvars
  kubernetes/config.aat.yaml
Labels: ns:sscs-bulk-scan-pr-151

#161 Pass common_tags to key-vault module
  build.gradle
  infrastructure/main.tf
  src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
Labels: ns:sscs-bulk-scan-pr-161

#162 Remove unnecessary json dependencies
  build.gradle
Labels: ns:sscs-bulk-scan-pr-162

#97 SSCS-4087 add nightly zap tests
  Jenkinsfile_nightly
  functional-output/.gitignore
  security.sh
Labels: ns:sscs-bulk-scan-pr-97
