Repository hmcts/sscs-bulk-scan, pull requests merged in 2019-10, with the labels that each got.

#381 Bump versions
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
  lib/applicationinsights-agent-2.3.1.jar
  lib/applicationinsights-agent-2.4.1.jar
  web.config
Labels: ns:sscs-bulk-scan-pr-381

#380 Swap bulk-scan to AKS on AAT only
  Jenkinsfile_CNP
  build.gradle
Labels: ns:sscs-bulk-scan-pr-380

#388 SSCS-6624 TYA – Hearing details page isn’t populated with dynamic dat…
  build.gradle
Labels: ns:sscs-bulk-scan-pr-388

#391 Suppress jackson
  config/owasp/suppressions.xml
Labels: ns:sscs-bulk-scan-pr-391

#379 set all links to false
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/SscsBulkScanFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java
Labels: ns:sscs-bulk-scan-pr-379

#394 Disable ASE
  Jenkinsfile_CNP
Labels: ns:sscs-bulk-scan-pr-394

#396 Enable ase on demo
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:sscs-bulk-scan-pr-396

#399 SSCS-6669 - suppress CVE-2019-17531 till the end of the month
  config/owasp/suppressions.xml
Labels: ns:sscs-bulk-scan-pr-399

#400 Remove old terraform files after aks migration
  infrastructure/aat.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  infrastructure/test_config.tf
Labels: ns:sscs-bulk-scan-pr-400

#402 Move enable_ase field
  infrastructure/main.tf
Labels: ns:sscs-bulk-scan-pr-402

#405 Add dependabot config
  .dependabot/config.yml
Labels: ns:sscs-bulk-scan-pr-405

#406 Revert change to remove managed_identity_object_id for each env
  infrastructure/aat.tfvars
  infrastructure/prod.tfvars
Labels: ns:sscs-bulk-scan-pr-406

#398 SSCS-6669 - add DirectionType
  build.gradle
Labels: ns:sscs-bulk-scan-pr-398
