Repository hmcts/sscs-bulk-scan, pull requests merged in 2019-05, with the labels that each got.

#205 Upgrade common to 2.0.7
  Jenkinsfile_CNP
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs-bulk-scan-pr-205

#215 helm charts
  Jenkinsfile_CNP
  build.gradle
  charts/sscs-bulk-scan/Chart.yaml
  charts/sscs-bulk-scan/requirements.yaml
  charts/sscs-bulk-scan/values.aat.template.yaml
  charts/sscs-bulk-scan/values.template.yaml
  kubernetes/deployment.template.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:sscs-bulk-scan-pr-215

#175 Sscs 5372 invalid filenames
  src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs-bulk-scan-pr-175

#217 Suppress CVE-2019-10247
  config/owasp/suppressions.xml
Labels: ns:sscs-bulk-scan-pr-217

#219 Update idam url for demo env
  infrastructure/demo.tfvars
Labels: ns:sscs-bulk-scan-pr-219

#225 SSCS-5451 Add test issuing office
  src/main/resources/application.yaml
Labels: ns:sscs-bulk-scan-pr-225

#235 SSCS-5693 Move robotics code to evidence share if feature flag on
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
Labels: ns:sscs-bulk-scan-pr-235
