Repository hmcts/sscs-bulk-scan, pull requests merged in 2019-08, with the labels that each got.

#305 Update sidam config
  src/main/resources/application.yaml
Labels: ns:sscs-bulk-scan-pr-305

#309 Suppress jackson cve
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs-bulk-scan-pr-309

#317 Warn when phone number greater than 11 digits
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs-bulk-scan-pr-317

#315 SSCS-6255 Reference data – Update sscs-venues.csv (change needed by 1…
  build.gradle
Labels: ns:sscs-bulk-scan-pr-315

#318 remove deprecated config
  Jenkinsfile_CNP
Labels: ns:sscs-bulk-scan-pr-318

#312 SSCS-6264 - update sscs-common version
  build.gradle
Labels: ns:sscs-bulk-scan-pr-312

#324 SSCS-6407 Set case code for new case
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
Labels: ns:sscs-bulk-scan-pr-324
