Repository hmcts/sscs-bulk-scan, pull requests merged in 2019-11, with the labels that each got.

#417 Use READY_TO_LIST_OFFICES env variable
  config/owasp/suppressions.xml
  src/main/resources/application.yaml
Labels: ns:sscs-bulk-scan-pr-417

#424 sscs-6928 Deploy to ASE demo
  Jenkinsfile_CNP
  config/owasp/suppressions.xml
Labels: ns:sscs-bulk-scan-pr-424

#423 SSCS-6839 Clear interloc review state
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java
  src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackController.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
Labels: ns:sscs-bulk-scan-pr-423

#428 turn on ready to list feature on demo
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:sscs-bulk-scan-pr-428

#427 SSCS-6791 SYA/tribunal case API – Change Norwich DRT to Sheffield DRT…
  build.gradle
Labels: ns:sscs-bulk-scan-pr-427

#431 SSCS-6836 Add missing fields to java model
  build.gradle
  charts/sscs-bulk-scan/Chart.yaml
Labels: ns:sscs-bulk-scan-pr-431
