Repository hmcts/sscs-bulk-scan, pull requests merged in 2019-07, with the labels that each got.

#267 SSCS-5996 - add dwp office
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs-bulk-scan-pr-267

#269 turn on send to Dwp
  infrastructure/prod.tfvars
Labels: ns:sscs-bulk-scan-pr-269

#277 extra logging in AAT
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
Labels: ns:sscs-bulk-scan-pr-277

#281 SSCS-5963 - update sscs-robotics-common version
  build.gradle
Labels: ns:sscs-bulk-scan-pr-281

#282 SSCS-4067 - update sscs-common rc version
  build.gradle
Labels: ns:sscs-bulk-scan-pr-282

#289 SSCS-6083 Remove DWP feature flag
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  build.gradle
  charts/sscs-bulk-scan/values.preview.template.yaml
  charts/sscs-bulk-scan/values.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/integrationTest/resources/mappings/create-case-invalid-robotics-200-response.json
  src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
Labels: ns:sscs-bulk-scan-pr-289

#292 Add Application Insights config
  lib/applicationinsights-agent-2.3.1.jar
  web.config
Labels: ns:sscs-bulk-scan-pr-292

#294 SSCS-6161 - fix build pipeline issue
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs-bulk-scan-pr-294

#296 SSCS-6071 - update sscs-common version
  build.gradle
Labels: ns:sscs-bulk-scan-pr-296

#301 SSCS-6103 Update image location to hmctspublic
  charts/sscs-bulk-scan/Chart.yaml
  charts/sscs-bulk-scan/requirements.yaml
  charts/sscs-bulk-scan/values.yaml
Labels: ns:sscs-bulk-scan-pr-301

#302 Update docker varibles
  Dockerfile
  charts/sscs-bulk-scan/values.yaml
  lib/AI-Agent.xml
Labels: ns:sscs-bulk-scan-pr-302

#303 Change ai-agent xml
  lib/AI-Agent.xml
Labels: ns:sscs-bulk-scan-pr-303
