Repository hmcts/sscs-bulk-scan, pull requests merged in 2020-07, with the labels that each got.

#474 SSCS-7187 Remove generated fields
  src/integrationTest/resources/mappings/create-case-200-response.json
  src/integrationTest/resources/mappings/exception/case-creation-request.json
  src/integrationTest/resources/mappings/exception/case-incomplete-creation-request-old.json
  src/integrationTest/resources/mappings/exception/case-incomplete-response.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request-old.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-response.json
  src/integrationTest/resources/mappings/exception/valid-appeal-request-old.json
  src/integrationTest/resources/mappings/exception/valid-appeal-response.json
  src/integrationTest/resources/mappings/existing-case-details-200-response.json
  src/integrationTest/resources/mappings/update-case-request.json
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTestOld.java
  src/test/java/uk/gov/hmcts/reform/sscs/common/SampleCaseDataCreator.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTestOld.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-474

#586 SSCS-7730 - CCD UI – Have directionIssued validate prior to submitting the event
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-586

#598 SSCS-7703 - Upgrading to Java 11 - Bulk Scan
  Dockerfile
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-598

#590 SSCS-7751: IDAM/OIDC - get userInfo from token or from calling /o/use…
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-590

#610 fixed failed nightly job
  Jenkinsfile_nightly
  audit.json
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-610
