Repository hmcts/sscs-bulk-scan, pull requests merged in 2020-10, with the labels that each got.

#685 Sscs 7688 office invalid warning
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTestOld.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-685

#707 SSCS-8213: Tech debt – Upgrade Owasp to 6.x
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-707

#711 SSCS 8219 date warning message
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallbackOld.java
  src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTestOld.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-711

#724 Supress tomcat package
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-724

#725 SSCS-8133 - Enable UC locally
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-725

#719 SSCS-8214 bump common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-719

#727 SSCS-8349: Bulkscan – UC office blank then should not throw warning
  src/integrationTest/resources/mappings/ocr-validation/valid-ocr-data-for-uc.json
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-727
