Repository hmcts/sscs-bulk-scan, pull requests merged in 2020-08, with the labels that each got.

#611 SSCS-7672: Bulk scan - Cases with email addresses populated are not a…
  src/integrationTest/resources/mappings/exception/case-creation-request.json
  src/integrationTest/resources/mappings/exception/case-incomplete-creation-request-old.json
  src/integrationTest/resources/mappings/exception/case-incomplete-response.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request-old.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-response.json
  src/integrationTest/resources/mappings/exception/valid-appeal-request-old.json
  src/integrationTest/resources/mappings/exception/valid-appeal-response.json
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTestOld.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-611

#614 SSCS-7803 - RPC is capturing Appointee address instead of Appellant address
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTestOld.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-614

#627 Nightly functional test setup
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-627

#628 load vault secrets
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-628

#630 Remove s from test url
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-630

#631 SSCS-7535 Up commons to include isScottish
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-631

#636 added more url
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-636

#639 fixed the proxy error
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-639

#623 SSCS-7309 - Set 'Previous State' field when case moves to dormant
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-623

#638 SSCS-7774 - Bulk scan/Validation – Rep name details blocks validation
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-638

#648 Remove unused tf remote state
  infrastructure/state.tf
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-648

#647 SSCS-7930 Removing invalid comma from JSON
  src/functionalTest/resources/import/all_fields_entered.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-647

#603 SSCS-7692 - Bulk scan – Validate post codes for all users
  src/functionalTest/resources/exception/all_fields_entered.json
  src/functionalTest/resources/exception/invalid_mobile_number.json
  src/functionalTest/resources/exception/mrn_date_greater_than_13_months.json
  src/functionalTest/resources/exception/some_mandatory_fields_missing.json
  src/functionalTest/resources/import/all_fields_entered.json
  src/functionalTest/resources/import/mrn_date_greater_than_13_months.json
  src/functionalTest/resources/import/some_mandatory_fields_missing.json
  src/functionalTest/resources/import/validate_appeal_created_case_request.json
  src/functionalTest/resources/validation/valid-ocr-form-data.json
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java
  src/integrationTest/resources/mappings/ocr-validation/invalid-ocr-data-transformation.json
  src/integrationTest/resources/mappings/ocr-validation/invalid-ocr-data-validation.json
  src/integrationTest/resources/mappings/ocr-validation/valid-ocr-data.json
  src/integrationTest/resources/mappings/validation/validate-appeal-created-case-request.json
  src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-and-appointee-request.json
  src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appointee-request.json
  src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-representative-request.json
  src/integrationTest/resources/mappings/validation/validate-interloc-appeal-created-case-request.json
  src/main/java/uk/gov/hmcts/reform/sscs/validators/PostcodeValidator.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/validators/PostcodeValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTestOld.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-603

#651 updated Hight to Medium
  audit.json
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-651
