Repository hmcts/sscs-bulk-scan, pull requests merged in 2020-11, with the labels that each got.

#722 SSCS-8330 Move to Elastic Search
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallbackOld.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/helper/TestConstants.java
  src/integrationTest/resources/mappings/existing-case-details-200-response.json
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-722

#736 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-736

#737 SSCS-8348 - Update Venue Data
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-737

#734 SSCS-8217 Address Validation
  src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-734

#750 Suppress for nightly builds
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-750

#749 Sscs 8136 no mrn date or office
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/validators/CaseValidator.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTestOld.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTestOld.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-749

#755 SSCS-7789 common update
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-755
