Repository hmcts/sscs-bulk-scan, pull requests merged in 2020-12, with the labels that each got.

#760 SSCS-8424 - Remove UC flag
  build.gradle
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-760

#771 Upgrade groovy
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-771

#773 Sscs 8255 app insight bulk scan
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-773
