Repository hmcts/sscs-bulk-scan, pull requests merged in 2020-05, with the labels that each got.

#528 SSCS-7411: Bulk scan – Null pointer thrown when trying to obtain the …
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
Labels: ns:sscs, rel:sscs-bulk-scan-pr-528

#532 SSCS-7481 Sheffield DRT changes
  build.gradle
Labels: ns:sscs, rel:sscs-bulk-scan-pr-532

#539 SSCS-7482: SYA/tribunal case API/bulk-scan – Change Watford DRT to Sh…
  build.gradle
  src/integrationTest/resources/mappings/exception/case-creation-request.json
  src/integrationTest/resources/mappings/exception/case-incomplete-creation-request-old.json
  src/integrationTest/resources/mappings/exception/case-incomplete-response.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request-old.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-response.json
  src/integrationTest/resources/mappings/exception/valid-appeal-request-old.json
  src/integrationTest/resources/mappings/exception/valid-appeal-response.json
  src/integrationTest/resources/mappings/update-case-request.json
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTestOld.java
Labels: ns:sscs, rel:sscs-bulk-scan-pr-539

#546 Add Bulk scan processor to the allowed services list
  src/main/resources/application.yaml
Labels: ns:sscs, rel:sscs-bulk-scan-pr-546

#552 Upgrade gradle 6.4
  Jenkinsfile_CNP
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:sscs, rel:sscs-bulk-scan-pr-552

#553 Bulk scan migration fix
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationController.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
Labels: ns:sscs, rel:sscs-bulk-scan-pr-553

#554 Add Bulk scan orchestrator service to the allowed services list
  src/main/resources/application.yaml
Labels: ns:sscs, rel:sscs-bulk-scan-pr-554

#555 Bump jackson 2.11.0
  build.gradle
Labels: ns:sscs, rel:sscs-bulk-scan-pr-555
