Repository hmcts/sscs-bulk-scan, pull requests merged in 2020-06, with the labels that each got.

#556 SSCS-7550: New AirLookup
  build.gradle
Labels: ns:sscs, rel:sscs-bulk-scan-pr-556

#567 Remove suppressions
  config/owasp/suppressions.xml
Labels: ns:sscs, rel:sscs-bulk-scan-pr-567

#568 SSCS-7587 - Upgrade java chart. Add renovate
  .github/renovate.json
  build.gradle
  charts/sscs-bulk-scan/Chart.yaml
  charts/sscs-bulk-scan/requirements.yaml
Labels: ns:sscs, rel:sscs-bulk-scan-pr-568

#571 SSCS-7418 Integrate HMCTS Java plugin
  build.gradle
Labels: ns:sscs, rel:sscs-bulk-scan-pr-571

#566 SSCS-7576 Bump SSCS-Common
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallbackOld.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-566

#561 SSCS-7527: Remove the SendToDWP event from code
  src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-561

#576 Remove unused suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-576

#583 SSCS-7712: Caseloader – Re-requesting a new IDAM token before updatin…
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-583
