Repository hmcts/sscs-bulk-scan, pull requests merged in 2021-03, with the labels that each got.

#832 SSCS-8750 - Dwp Document Sorting
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-832

#835 CVE-2021-22112
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-835

#836 fix ref
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-836

#840 Fix dependency check
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-840

#844 upgraded tomcat version to fix dependency check
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-844

#852 SSCS-8864: Following tests are failing on bulk-scan nightly build
  Jenkinsfile_parameterized
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-852

#862 SSCS-8864: Following tests are failing on bulk-scan nightly build
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/OcrFormValidationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/ValidateSscsCaseFunctionalTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-862

#837 fix cnp azure version
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-837

#865 SSCS-8864: Following tests are failing on bulk-scan nightly build
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-865

#866 SSCS-8864: Following tests are failing on bulk-scan nightly build
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/OcrFormValidationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/ValidateSscsCaseFunctionalTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-866

#873 upgrade pdfbox dependency
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-873

#872 Remove unused suppressions
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-872

#875 SSCS-8999: Fix Functional tests on bulk-scan nightly build
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-875

#876 Sscs 8999
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/OcrFormValidationFunctionalTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-876

#879 Bump rest-assured 4.3.3
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-879

#883 DTSPO-1792 Switch bintray to jitpack
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-883
