Repository hmcts/sscs-bulk-scan, pull requests merged in 2021-09, with the labels that each got.

#1040 SSCS-9567: P1 – Flag to tell users that a case has been affected by t…
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1040

#1041 Updated provider version
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1041

#1044 SSCS-9437 Bulk scan – Upgrade org.springframework to v5.3.9
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1044

#1055 Revert "SSCS-9437 Bulk scan – Upgrade org.springframework to v5.3.9"
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1055

#1054 SSCS-9564 Other party name
  src/functionalTest/resources/exception/output/sscs2_expected_all_fields_entered.json
  src/functionalTest/resources/exception/sscs2_all_fields_entered.json
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java
  src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json
  src/integrationTest/resources/mappings/ocr-validation/sscs2-invalid-ocr-data.json
  src/integrationTest/resources/mappings/ocr-validation/sscs2-valid-ocr-data.json
  src/integrationTest/resources/mappings/validation/sscs2-validate-appeal-created-case-request.json
  src/integrationTest/resources/mappings/validation/sscs2-validate-appeal-created-missing-child-maintenance.json
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/main/resources/schema/sscs2-bulk-scan-schema.json
  src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1054

#1033 SSCS-9348 - Keep environment specific branches in sync with master
  Jenkinsfile_CNP
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1033

#1051 SSCS-9562 Added SSCS2 handling
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/test/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1051
