Repository hmcts/sscs-bulk-scan, pull requests merged in 2021-05, with the labels that each got.

#898 SSCS-8900 - Attendance Allowance - Airlookup, DWP addresses & Robot Configuration
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-898

#924 Suppress false positive CVE-2020-7791 since it is a C# CVE
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java
  src/functionalTest/resources/exception/all_fields_entered.json
  src/functionalTest/resources/exception/all_fields_entered_uc.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered_uc.json
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json
  src/integrationTest/resources/mappings/exception/valid-appeal-response.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-924

#927 sscs 9066 removed bintray moved to jitpack refs
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-927

#938 Suppress low warnings, ticket raised to fixed this
  audit.json
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-938

#943 Fixed fortify issue
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-943

#942 SSCS-8906 Bereavement benefit DWP mappings
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-942

#935 SSCS-9184:Validate appeal
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-935

#940 SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-940
