Repository hmcts/sscs-bulk-scan, pull requests merged in 2021-06, with the labels that each got.

#950 Fix dependency check
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-950

#945 SSCS-8820 - JSA DWP Office Address
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-945

#977 update security script
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-977
