Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-03, with the labels that each got.

#1183 SSCS-10234-suppressed till the beginning of april
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1183

#1185 SSCS-9872-update-commons-version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1185

#1204 SSCS-10280: suppressing dependencies
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1204

#1205 SSCS-10297: suppressing dependencies
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1205

#1187 SSCS-11066-build gradle is updated to have new sscs common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1187

#1208 SSCS-10318: update commons and POI
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1208

#1147 SSCS-9902: Location data – Update airlookup to v15
  charts/sscs-bulk-scan/Chart.yaml
  charts/sscs-bulk-scan/values.yaml
  src/functionalTest/resources/exception/output/expected_all_fields_auto_office_ma.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered_aa.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered_uc.json
  src/functionalTest/resources/exception/output/expected_all_fields_pip_office_entered_aa.json
  src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months.json
  src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months_grounds_missing.json
  src/functionalTest/resources/exception/output/expected_some_mandatory_fields_missing.json
  src/functionalTest/resources/exception/output/sscs2_expected_all_fields_entered.json
  src/functionalTest/resources/exception/output/sscs5_expected_all_fields_entered.json
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json
  src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json
  src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1147

#1212 sscs 9902 added feature flag
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1212

#1213 Create CODEOWNERS
  CODEOWNERS
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1213
