Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-10, with the labels that each got.

#1301 SSCS-10830-ignore-previously-form-type
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/FormTypeValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/FormTypeValidatorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1301

#1331 Feature/sscs 10841 use epims id court venue
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1331

#1334 SSCS-10985 CVE Fix Commons Bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1334

#1342 Commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1342

#1343 SSCS-11008 - Add content type and tags
  .gitignore
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, add-or-update, rel:sscs-bulk-scan-pr-1343

#1344 SSCS-11063 Use Renovate Shared Preset
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1344
