Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-06, with the labels that each got.

#1273 SSCS-10445 Commons Bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1273

#1259 Update sscs common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1259

#1276 Update build.gradle
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1276

#1279 SSCS-10286 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1279

#1281 SSCS-10620 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1281

#1282 SSCS-10242 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1282

#1285 SSCS-10178 Commons Bump
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1285
