Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-05, with the labels that each got.

#1236 SSCS-10223 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1236

#1235 SSCS-10444 Change CVE Reporting
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1235

#1237 Azure tagging
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1237

#1240 suppressing dependency
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1240

#1245 SSCS-10490 bump common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1245

#1250 SSCS-10533: Supress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1250

#1249 SSCS-10490 fix feature flag for nightly builds
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1249

#1251 SSCS-10490 hoping this fixes the nightly build
  charts/sscs-bulk-scan/Chart.yaml
  charts/sscs-bulk-scan/values.aat.template.yaml
  charts/sscs-bulk-scan/values.preview.template.yaml
  charts/sscs-bulk-scan/values.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1251

#1254 SSCS-10552: Upgrading Tomcat
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1254

#1257 Remove CAM nightly flag
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1257

#1258 SSCS-10116 Bump SSCS Commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1258

#1253 SSCS-10517 change mentions of work allocation to cam
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1253

#1263 Update Common
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/OcrFormValidationFunctionalTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1263
