Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-04, with the labels that each got.

#1214 Update build.gradle
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/resources/exception/output/expected_all_fields_auto_office_ma.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered_aa.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered_uc.json
  src/functionalTest/resources/exception/output/expected_all_fields_pip_office_entered_aa.json
  src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months.json
  src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months_grounds_missing.json
  src/functionalTest/resources/exception/output/expected_some_mandatory_fields_missing.json
  src/functionalTest/resources/exception/output/sscs2_expected_all_fields_entered.json
  src/functionalTest/resources/exception/output/sscs5_expected_all_fields_entered.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-response-attendance-allowance.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-response.json
  src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/valid-appeal-response.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1214

#1221 SSCS-10220 Update to common RC version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1221

#1218 sscs-10146 update sscs-common RC version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1218

#1230 SSCS-10387 Update Commons
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1230
