Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-12, with the labels that each got.

#1377 SSCS-11165 : Added pre commit hooks
  build.gradle
  config/git/pre-commit
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1377

#1380 cve's suppression
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1380

#1379 SSCS-11165 : Updated windows variable
  config/git/pre-commit
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1379
