Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-09, with the labels that each got.

#1311 Feature/sscs 10841 use epims id court venue
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1311

#1314 Revert "Feature/sscs 10841 use epims id court venue"
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1314

#1316 SSCS-10841 Revert common change
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1316

#1317 SSCS-10818 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1317

#1318 SSCS-10901 Configure renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1318

#1313 SSCS-10860 - Upgrade of libraries
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1313

#1315 SSCS-10882 Fixing Conflicting IDs
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json
  src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1315

#1332 SSCS-10906 Long-term snakeyaml suppression
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1332
