Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-02, with the labels that each got.

#1157 sscs 9909 handle blank benefit types
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1157

#1163 update sscs-common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1163

#1175 Surpress dependency issues
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1175

#1173 SSCS - 10070 - Change data in 'caseAccessCategory' field
  build.gradle
  src/functionalTest/resources/exception/output/expected_all_fields_auto_office_ma.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered_aa.json
  src/functionalTest/resources/exception/output/expected_all_fields_entered_uc.json
  src/functionalTest/resources/exception/output/expected_all_fields_pip_office_entered_aa.json
  src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months.json
  src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months_grounds_missing.json
  src/functionalTest/resources/exception/output/expected_some_mandatory_fields_missing.json
  src/functionalTest/resources/exception/output/sscs2_expected_all_fields_entered.json
  src/functionalTest/resources/exception/output/sscs5_expected_all_fields_entered.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-response-attendance-allowance.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json
  src/integrationTest/resources/mappings/exception/case-incomplete-response.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-response.json
  src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/valid-appeal-response.json
  src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1173

#1179 upgrading Log4j to 2.17.1
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1179
