Repository hmcts/sscs-bulk-scan, pull requests merged in 2022-08, with the labels that each got.

#1298 SSCS-10805-extend-suppression-date
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1298

#1299 SSCS-10805- update-jar-version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1299

#1303 SSCS-10773: Update commons version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1303

#1308 chore: increment sscs-common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1308

#1309 Add backstage configuration file
  catalog-info.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1309

#1302 SSCS-9874-common-version-update
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1302

#1305 SSCS-10841 Use epims ID to resolve court venue.
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1305

#1310 Revert "SSCS-10841 Use epims ID to resolve court venue."
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1310
