Repository hmcts/sscs-bulk-scan, pull requests merged in 2023-10, with the labels that each got.

#1461 Update renovate and suppressions
  .github/renovate.json
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1461

#1463 SSCSCI-12: suppress CVEs
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1463

#1464 SSCSCI-12
  audit.json
  build.gradle
  charts/sscs-bulk-scan/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1464
