Repository hmcts/sscs-bulk-scan, pull requests merged in 2023-08, with the labels that each got.

#1449 Java 17 fix
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/sscs-bulk-scan/Chart.yaml
  charts/sscs-bulk-scan/values.yaml
  infrastructure/main.tf
  infrastructure/state.tf
  lib/applicationinsights.json
Labels: ns:sscs, prd:sscs, add-or-update, rel:sscs-bulk-scan-pr-1449

#1450 Appinsights fix
  lib/applicationinsights.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1450

#1452 CVEFix 04.08.2023
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1452
