Repository hmcts/sscs-bulk-scan, pull requests merged in 2023-04, with the labels that each got.

#1424 Supressions
  charts/sscs-bulk-scan/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1424

#1426 Spring update and suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1426

#1427 RemovalSecurityShFile
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1427

#1429 RemovalSecurityShFile
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1429

#1430 Security Scan Fix
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1430

#1431 suppress dependencies
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1431
