Repository hmcts/sscs-bulk-scan, pull requests merged in 2024-12, with the labels that each got.

#1535 Bump common as new event type is added
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1535

#1536 SSCSCI-1214 commons bump to pr
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1536

#1537 Validate port of entry for non-mainland UK addresses
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/AppealPostcodeHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/AppealPostcodeHelperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1537

#1538 SSCSSI-247: Update to sscs commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1538

#1539 SSCSCI-1347 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1539

#1540 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1540
