Repository hmcts/sscs-bulk-scan, pull requests merged in 2024-11, with the labels that each got.

#1515 SSCSCI-995-jackson-databind-bump
  build.gradle
  config/checkstyle/checkstyle.xml
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/domain/CaseResponse.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackController.java
  src/main/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationController.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/validation/OcrDataValidationRequest.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-bulk-scan-pr-1515

#1524 SSCSSI-98-21: C4: hearingBooked - ProcessHmcMessageService
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1524

#1523 SSCSCI-1385 security scan fix
  audit.json
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-bulk-scan-pr-1523

#1526 Add sampling for health requests
  lib/applicationinsights.json
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1526

#1527 Upgrade app insights to latest
  Dockerfile
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1527

#1517 SSCSCI-1128
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-bulk-scan-pr-1517

#1530 Bump common to latest version(include enum changes for add hearing outcome)
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1530

#1531 SSCSCI-1406: Bumping up commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1531

#1533 SSCSCI-1406-fix: bumping up commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1533
