Repository hmcts/sscs-bulk-scan, pull requests merged in 2025-03, with the labels that each got.

#1562 SSCSCI-1778
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1562

#1560 test common elastic search changes
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1560

#1565 SSCSCI-1719 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1565

#1552 SSCSCI-1599
  src/integrationTest/resources/mappings/exception/auto-case-incomplete-response.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-response-attendance-allowance.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json
  src/integrationTest/resources/mappings/exception/case-creation-request.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request-old.json
  src/integrationTest/resources/mappings/exception/case-non-compliant-response.json
  src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json
  src/integrationTest/resources/mappings/exception/valid-appeal-request-old.json
  src/integrationTest/resources/mappings/exception/valid-appeal-response.json
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/validators/CaseValidator.java
  src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java
  src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
  src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java
  src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
  src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java
  src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1552
