Repository hmcts/sscs-bulk-scan, pull requests merged in 2025-01, with the labels that each got.

#1541 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1541

#1542 SSCSCI-1428: sscs-common bump
  build.gradle
Labels: ns:sscs, prd:sscs

#1543 SSCSCI-1205: update sscs-common
  build.gradle
Labels: ns:sscs, prd:sscs

#1545 SSCSCI-1531
  build.gradle
Labels: ns:sscs, prd:sscs

#1546 SSCSCI-1607 Spring Boot 3 migration
  .travis.yml
  build.gradle
  charts/sscs-bulk-scan/Chart.yaml
  charts/sscs-bulk-scan/values.preview.template.yaml
  charts/sscs-bulk-scan/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/WebConfiguration.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-bulk-scan-pr-1546
